// Mocks generated by Mockito 5.4.0 from annotations
// in futurama_quiz/test/unit_tests/futurama_data_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:futurama_quiz/api/futurama_provider.dart' as _i2;
import 'package:futurama_quiz/models/character/character.dart' as _i5;
import 'package:futurama_quiz/repository/futurama_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuturamaApiService_0 extends _i1.SmartFake
    implements _i2.FuturamaApiService {
  _FakeFuturamaApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FuturamaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFuturamaRepository extends _i1.Mock
    implements _i3.FuturamaRepository {
  MockFuturamaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FuturamaApiService get futuramaApiService => (super.noSuchMethod(
        Invocation.getter(#futuramaApiService),
        returnValue: _FakeFuturamaApiService_0(
          this,
          Invocation.getter(#futuramaApiService),
        ),
      ) as _i2.FuturamaApiService);
  @override
  _i4.Future<List<_i5.Character>> fetchCharacters() => (super.noSuchMethod(
        Invocation.method(
          #fetchCharacters,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Character>>.value(<_i5.Character>[]),
      ) as _i4.Future<List<_i5.Character>>);
}
